[template]
src = "application.properties.tmpl"
dest = "/etc/conf/gaian/content-service/application.properties"
prefix = "/dev/content-service"

keys= ['/spring.application.name',
'/spring.profiles.active', 
'/rest.client.connection.timeout', 
'/rest.read.timeout', 
'/rest.connection.request.timeout', 
'/spring.banner.charset', 
'/spring.banner.location', 
'/spring.datasource.url', 
'/spring.datasource.username', 
'/spring.datasource.password', 
'/spring.datasource.driver-class-name', 
'/spring.datasource.validationQuery', 
'/spring.jpa.show-sql', 
'/spring.jpa.properties.hibernate.dialect', 
'/spring.jpa.properties.hibernate.format_sql', 
'/spring.jpa.hibernate.ddl-auto', 
'/spring.servlet.multipart.enabled', 
'/spring.servlet.multipart.file-size-threshold', 
'/spring.servlet.multipart.max-file-size', 
'/spring.servlet.multipart.max-request-size', 
'/files.upload-dir', 
'/nginx.scheme', 
'/nginx.host', 
'/nginx.port', 
'/nginx.path', 
'/content.scheme', 
'/content.host', 
'/content.port', 
'/content.path', 
'/hls.enabled', 
'/hls.kafka.topic', 
'/hls.kafka.bootstrap.servers', 
'/kafka.servers.autocommit', 
'/kafka.servers.timeout', 
'/kafka.servers.commitinterval', 
'/hls.kafka.servers.groupid', 
'/kafka.servers.offsetreset', 
'/hls.profiles.count', 
'/hls.vprofile', 
'/hls.vcodec', 
'/hls.format', 
'/hls.resolution', 
'/hls.video.bitrate', 
'/hls.fps', 
'/hls.acodec', 
'/hls.audio.bitrate', 
'/hls.audio.chanel.layout', 
'/hls.aspectratio', 
'/hls.vlevel', 
'/gps.event.type', 
'/hls.supported.video.extensions', 
'/content.metadata.prefix',
'/endpoints.sensitive',
'/endpoints.actuator.enabled',
'/management.security.enabled',
'/management.endpoint.metrics.enabled',
'/management.endpoints.web.exposure.include',
'/spring.cloud.consul.enabled',
'/spring.cloud.consul.host',
'/spring.cloud.consul.port',
'/spring.cloud.consul.discovery.register',
'/management.metrics.tags.application']
